// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfQo1hPv5fF7qNh-gS5xhl8SxpdEVZtv8',
    appId: '1:726014776484:web:db7b296748a7b519514231',
    messagingSenderId: '726014776484',
    projectId: 'provider-auth-app-c8fbc',
    authDomain: 'provider-auth-app-c8fbc.firebaseapp.com',
    storageBucket: 'provider-auth-app-c8fbc.appspot.com',
    measurementId: 'G-BM43100QXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWdRcRhOf_WHMPNnIR4BJF-pe6RDH0yqw',
    appId: '1:726014776484:android:3c8408d6a0effce0514231',
    messagingSenderId: '726014776484',
    projectId: 'provider-auth-app-c8fbc',
    storageBucket: 'provider-auth-app-c8fbc.appspot.com',
  );
}
